// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDffKQmRkVsDHqDxnO-o6FpDVLaDsY1Nxw',
    appId: '1:494990111842:web:1f437095f353b4ff314d3b',
    messagingSenderId: '494990111842',
    projectId: 'mpit-71dfe',
    authDomain: 'mpit-71dfe.firebaseapp.com',
    storageBucket: 'mpit-71dfe.appspot.com',
    measurementId: 'G-RR520FH9C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeWvE0VFo_OOCqit-jvAnOUGLbSKbCBFo',
    appId: '1:494990111842:android:509bd8a9a196f394314d3b',
    messagingSenderId: '494990111842',
    projectId: 'mpit-71dfe',
    storageBucket: 'mpit-71dfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtMfv_TgzKsVchSRHlyOFy8NT7Nocpvgw',
    appId: '1:494990111842:ios:ab4f67e681b4b011314d3b',
    messagingSenderId: '494990111842',
    projectId: 'mpit-71dfe',
    storageBucket: 'mpit-71dfe.appspot.com',
    iosClientId: '494990111842-99ie6d8e2aq7g734lvc7dj53il3dm606.apps.googleusercontent.com',
    iosBundleId: 'com.example.mpit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtMfv_TgzKsVchSRHlyOFy8NT7Nocpvgw',
    appId: '1:494990111842:ios:ab4f67e681b4b011314d3b',
    messagingSenderId: '494990111842',
    projectId: 'mpit-71dfe',
    storageBucket: 'mpit-71dfe.appspot.com',
    iosClientId: '494990111842-99ie6d8e2aq7g734lvc7dj53il3dm606.apps.googleusercontent.com',
    iosBundleId: 'com.example.mpit',
  );
}
